"""add foreign key to community messages user

Revision ID: 4cd4f285cbd0
Revises: eaccbe90de9b
Create Date: 2026-05-09 13:35:11.191207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd4f285cbd0'
down_revision: Union[str, Sequence[str], None] = 'eaccbe90de9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_messages_user_id'), table_name='community_messages')
    op.create_foreign_key(None, 'community_messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community_messages', type_='foreignkey')
    op.create_index(op.f('ix_community_messages_user_id'), 'community_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###
