"""create allergens table

Revision ID: 680662713b0f
Revises: 1fe4569fc804
Create Date: 2026-02-05 19:02:49.183113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680662713b0f'
down_revision: Union[str, Sequence[str], None] = '1fe4569fc804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergens_id'), 'allergens', ['id'], unique=False)
    op.create_index(op.f('ix_allergens_name'), 'allergens', ['name'], unique=True)
    op.create_table('user_allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'allergen_id', name='uq_user_allergen')
    )
    op.create_index(op.f('ix_user_allergens_allergen_id'), 'user_allergens', ['allergen_id'], unique=False)
    op.create_index(op.f('ix_user_allergens_id'), 'user_allergens', ['id'], unique=False)
    op.create_index(op.f('ix_user_allergens_user_id'), 'user_allergens', ['user_id'], unique=False)
    op.create_table('food_allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'allergen_id', name='uq_food_allergen')
    )
    op.create_index(op.f('ix_food_allergens_allergen_id'), 'food_allergens', ['allergen_id'], unique=False)
    op.create_index(op.f('ix_food_allergens_food_id'), 'food_allergens', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_allergens_id'), 'food_allergens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_allergens_id'), table_name='food_allergens')
    op.drop_index(op.f('ix_food_allergens_food_id'), table_name='food_allergens')
    op.drop_index(op.f('ix_food_allergens_allergen_id'), table_name='food_allergens')
    op.drop_table('food_allergens')
    op.drop_index(op.f('ix_user_allergens_user_id'), table_name='user_allergens')
    op.drop_index(op.f('ix_user_allergens_id'), table_name='user_allergens')
    op.drop_index(op.f('ix_user_allergens_allergen_id'), table_name='user_allergens')
    op.drop_table('user_allergens')
    op.drop_index(op.f('ix_allergens_name'), table_name='allergens')
    op.drop_index(op.f('ix_allergens_id'), table_name='allergens')
    op.drop_table('allergens')
    # ### end Alembic commands ###
