"""add community messages

Revision ID: 857e6bd481ef
Revises: 61f2a796e884
Create Date: 2026-02-22 16:26:15.612392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857e6bd481ef'
down_revision: Union[str, Sequence[str], None] = '61f2a796e884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_messages_id'), 'community_messages', ['id'], unique=False)
    op.create_index(op.f('ix_community_messages_room_id'), 'community_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_community_messages_user_id'), 'community_messages', ['user_id'], unique=False)
    op.create_index('ix_community_room_created', 'community_messages', ['room_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_community_room_created', table_name='community_messages')
    op.drop_index(op.f('ix_community_messages_user_id'), table_name='community_messages')
    op.drop_index(op.f('ix_community_messages_room_id'), table_name='community_messages')
    op.drop_index(op.f('ix_community_messages_id'), table_name='community_messages')
    op.drop_table('community_messages')
    # ### end Alembic commands ###
